apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/jagasworld/rollout-demo.git
      revision: HEAD
      # Use the 'files' generator to find files matching this path
      files:
      - path: "argo-apps/*.yaml"

  template:
    metadata:
      # Name the Application based on the filename (e.g., 'rollout-demo')
      name: '{{path.basename | trimSuffix "-application.yaml"}}'
    spec:
      project: default
      
      # The 'source' block will be filled in from the content of the matched files
      source:
        # These values are inherited from the 'generators' section
        repoURL: '{{ .repoURL }}'
        targetRevision: '{{ .targetRevision }}'
        # The 'path' is read directly from the content of each YAML file found
        path: '{{ .source.path }}' 

      destination:
        server: 'https://kubernetes.default.svc'
        # Creates a namespace based on the app name, e.g., 'rollout-demo'
        namespace: '{{path.basename | trimSuffix "-application.yaml"}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true