apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/jagasworld/rollout-demo.git
      revision: HEAD
      files:
      - path: "argo-apps/*.yaml"

  template:
    metadata:
      # Use the dot prefix to access the 'name' field from the file
      name: '{{.name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/jagasworld/rollout-demo.git
        targetRevision: HEAD
        # Use the dot prefix to access the 'source.path' field from the file
        path: '{{.source.path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        # Use the dot prefix here as well
        namespace: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
