apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rollout-demo
  template:
    metadata:
      labels:
        app: rollout-demo
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:green  # Start with the "blue" version
        ports:
        - containerPort: 8080
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}  # Pause indefinitely until manually promoted
      - setWeight: 40
      - pause: {duration: 10} # Pause for 10 seconds
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-demo-active
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: rollout-demo
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-demo-preview
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: rollout-demo
