apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-rollout-demo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: ./rollout-demo-app-manifests/nginx/
    repoURL: https://github.com/jagasworld/rollout-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true